config/routes.rb
CarClub::Application.routes.draw do
  get "shows/new"
  get "shows/create"
  resources :cars
  get '/deals', to: 'deals#special_of_the_day'
  root to: 'deals#special_of_the_day'

end

app/models/car.rb
class Car < ActiveRecord::Base
  
  has_many :makes
  has_many :models, through: :makes
  
  validates_presence_of :full_name, :email
  
  def self.jeep
    where(make:'jeep')
  end  
  
end

app/models/make.rb
class Make < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'bootstrap'

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render action: 'show', status: :created, location: @car }
      else
        format.html { render action: 'new' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:year, :brand, :model, :description, :user)
    end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  
  def special_of_the_day
    @make_and_model = make.model
  end  
  
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper

  def brief_description car
    truncate car.description, length:20
  end
    
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Brand</th>
      <th>Model</th>
      <th>Description</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.year %></td>
        <td><%= car.brand %></td>
        <td><%= car.model %></td>
        <td><%= brief_description car %></td>
        <td><%= car.user %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @car.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Description:</strong>
  <%= @car.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @car.user %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/deals/special_of_the_day.html.erb
<html><h1>check back from a special deal!</h1></html>

app/views/layouts/_header.html.erb
<%= Time.now %>
<h1>page header</h1>
<p>Notice: <%= notice %></p>
<p>Alert: <%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarClub</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shows/create.html.erb
<h1>Shows#create</h1>
<p>Find me in app/views/shows/create.html.erb</p>

app/views/shows/new.html.erb
<h1> Apply for entry to Car Show</h1>
<%= form_for @show do |form| %>

  <%= form.label :make, "Enter make of auto" %>
  <%= form.text_field :make %>
  
  <br/>
  <%= form.label :model, "Enter model" %>
  <%= form.text_field :model %>
  
  <br/>
  <%= form.label :description %>
  <%= form.text_area :description %>

  <br/>

  <%= form.submit "Apply" %>

<% end -%>